[env]
MISE_GEM_INSTALL_OPTS = "--no-document"

[tools]
"aqua:rclone/rclone" = "latest"
"aqua:zellij-org/zellij" = "latest"
"neovim" = "latest"

"go" = { version = "latest" }

"dotnet" = { version = "latest" }

"ruby" = { version = "latest" }
"gem:rails" = { version = "latest" }
"gem:neovim" = { version = "latest" }

"node" = { version = "lts" }
"npm:npm" = { version = "latest" }
"npm:@anthropic-ai/claude-code" = { version = "latest" }
"npm:neovim" = { version = "latest" }
"npm:typescript" = { version = "latest" }
"npm:tree-sitter-cli" = { version = "latest" }
"npm:pnpm" = { version = "latest" }

"php" = { version = "latest" }
"rust" = { version = "latest", components = "rust-analyzer", targets = "wasm32-unknown-unknown,x86_64-pc-windows-gnu" }

