[font]
size = 14
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[[font.italic]]
family = "JetBrainsMono Nerd Font Mono"
style = "MediumItalic"

[[font.bold]]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"
