[font]
size = 16
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "JetBrainsMono Nerd Font Propo"
style = "Medium"

[[font.italic]]
family = "JetBrainsMono Nerd Font Propo"
style = "MediumItalic"

[[font.bold]]
family = "JetBrainsMono Nerd Font Propo"
style = "Bold"
